version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # 静的サイトのビルドやテストなど
      - npm install
      #- npm test
      - npm build
  build:
    commands:
      # npm run build の結果がdistディレクトリに出力されるという前提
      - aws s3 sync ./build s3://code-pipeline-tutorial-2021
# - aws cloudfront create-invalidation --distribution-id <キャッシュクリアするCloudFrontのDestributionID> --paths '/*'
