version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # 静的サイトのビルドやテストなど
      - npm install
      #- npm test
  build:
    commands:
      - npm build
      - aws s3 ls
  post_build:
    commands:
      - aws s3 sync /build s3://code-pipeline-tutorial-2021 --acl public-read
# - aws cloudfront create-invalidation --distribution-id <キャッシュクリアするCloudFrontのDestributionID> --paths '/*'
